### ISSUE TITLE
Make plot greyscale with cool orangutangs

### ISSUE THREAD

**Issue by ghost** [eugene-cs50/2022_06_30_carpentries#3]
https://github.com/eugene-cs50/2022_06_30_carpentries/blob/837cdba5d0ff5333e04547d796f83d270b96ed9e/output_species_count/species_counts.R#L67

Not all journals accept colour in 🥑 change to 🦧 to make it look happier and jolly!

**Comment by ZimbiliB** [comment]
Oooh, yes, actually, think rainbows will be much more fun. The journals don't have good taste, so instead of grayscale make it rainbowscale..
